# apt - Show versions with:
# apt-cache madison {{ app.name }} | awk '{print $3}'
# `apt policy {{ app.name }}` also works
---
applications:
  - name: openscad
    provider: flatpak
  - name: tmux
    provider: apt
