---
# the directory where executables (binaries, AppImages, etc) should be installed
# Ensure this directory is in your path
executable_directory: "{{ ansible_facts.env.HOME }}/.local/bin"

# all applications
# TODO: break out each application to its own file and load programatically
# so it's easier to merge PRs without a ton of merge conflicts
catalog:
  joplin:
    providers:
      flatpak:
        application_id: net.cozic.joplin_desktop
      github_AppImage:
        repo: github.com/laurent22/joplin
  prusaslicer:
    providers:
      flatpak:
        application_id: com.prusa3d.PrusaSlicer
      github_AppImage:
        repo: github.com/prusa3d/PrusaSlicer
  openscad:
    providers:
      flatpak:
        application_id: org.openscad.OpenSCAD
      apt:
        name: openscad
  tmux:
    providers:
      apt:
        name: tmux

# list of applications to install from providers
applications:
