---
install_dotfiles: True
hostname: phoenix
preferred_shell: /usr/bin/zsh

packages:
  # TODO: figure out how to configure
  - gnome-tweak-tool
  # http://www.nixnote.org/NixNote-Home/
  - nixnote2
  # https://zealdocs.org/
  - zeal