---
install_dotfiles: True
hostname: phoenix
preferred_shell: /usr/bin/zsh

packages:
  # TODO: dont forget my settings in dconf
  - gnome-tweak-tool
  # http://www.nixnote.org/NixNote-Home/
  - nixnote2
  # https://zealdocs.org/
  - zeal

firefox_profiles:
  default-release:
    extensions:
      # TODO: enable extensions after install. they are disabled by default
      - ublock-origin
      - tridactyl-vim
      - lastpass-password-manager
    preferences:
      privacy.donottrackheader.enabled: "true"
      privacy.trackingprotection.enabled: "true"
      signon.rememberSignons: "false"
      datareporting.healthreport.uploadEnabled: "false"
      browser.ctrlTab.recentlyUsedOrder: "false"
      browser.search.defaultenginename: "'DuckDuckGo'"
