---
your_full_name: Kent Brockman
your_email: brockman.ks@gmail.com
# name your computer
hostname: phoenix
install_dotfiles: True
preferred_shell: /usr/bin/zsh
install_battery_management_tools: true
sync_content: true

firefox_profiles:
  default-release:
    extensions:
      # TODO: enable extensions after install. they are disabled by default
      # TODO: automatically configure extentions (e.g. tridactyl-vim URL ignore list)
      - ublock-origin
      - tridactyl-vim
      - lastpass-password-manager
      - gnome-shell-integration
    preferences:
      privacy.donottrackheader.enabled: "true"
      privacy.trackingprotection.enabled: "true"
      signon.rememberSignons: "false"
      datareporting.healthreport.uploadEnabled: "false"
      browser.ctrlTab.recentlyUsedOrder: "false"
      browser.search.defaultenginename: "'DuckDuckGo'"
      browser.urlbar.matchBuckets: "general:5,suggestion:Infinity"

flatpak_applications:
  # sql database client
  - io.dbeaver.DBeaverCommunity
  # team chat
  - com.mattermost.Desktop
  # music client
  - com.spotify.Client
  # handy data science prototyping tool
  - org.octave.Octave

# all the applications you like and want managed by apt
apt_applications:
  # googles browser
  - google-chrome-stable
  # containerization engine + tooling
  - docker.io
  - docker-compose
  # team chat
  - slack-desktop
  # virtual machines
  - virtualbox
  # timer to help me work using pomodoro technique: https://en.wikipedia.org/wiki/Pomodoro_Technique
  - gnome-shell-pomodoro
  # view developer documentation offline. nice for working on an offline/airplane/roadtrip
  - zeal
  # image editor
  - gimp
  # for recording parts of screen and turning it into gifs
  - peek
  # great media player
  - vlc
  # typing tutor
  - gtypist
  # irc chat client
  - irssi
  # 3D parametric modelling
  - freecad
  # slicing software to turn 3d models into printable gcode
  - cura

binary_applications:
  - url: https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2020-03-14T01-23-37Z
    dest: ~/.local/bin/mc

# If using gnome, pick the extensions you like
# https://extensions.gnome.org/local/
# get id from extension URL
gnome_extension_ids:
  # Alt-Tab Switcher Popup Delay Removal
  - 1317
  # Sound Input & Output Device Chooser
  - 906
  # System Monitor
  # TODO: save configurations from dconf dump /org/gnome/shell/extensions/
  - 120
  # Open Weather
  - 750
  # Removable Drive Menu
  - 7
  # Automatic background slideshow
  - 543
  # Alt+Tab menu will not group applications
  # TODO: save configurations from dconf dump /org/gnome/shell/extensions/
  - 15
  # Clipboard history
  - 779
  # StealMyFocus - remove "Window is ready" notification and focus on it
  - 234
  # remove blur effect from lockscreen
  - 2935
  # gTile - specify window sizes nicely (if not using pop shell tiling)
  # - 28
  # reboot with options from grub
  # - 893

# links to debian packages to install
other_applications:
  # tool for making USB sticks that boot multiple OS's http://multibootusb.org
  # - https://github.com/mbusb/multibootusb/releases/download/v9.2.0/python3-multibootusb_9.2.0-1_all.deb

# gnome-desktop uses the dconf database under the hood for managing settings
# dconf is a key-value storage and how you specify values can be a little finicky
# see this for a good guide: https://docs.ansible.com/ansible/latest/modules/dconf_module.html#notes
# basically: make sure values have single quotes around them so ansibles dconf module parses them as strings
gnome_desktop_settings:
  # display temperatures in celsius
  - key: /org/gnome/GWeather/temperature-unit
    value: "'centigrade'"

  # invert scrolling so it is similar to MacOS. if you like windows scrolling set to false
  - key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
    value: "true"
    # use two fingers on the track pad to scroll
  - key: /org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled
    value: "true"

  # enable f.lux style blue-light reduction in display after sundown
  - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: "true"

  # enable location services
  - key: /org/gnome/system/location
    value: "true"

  # determine where in the world we are for weather purposes
  - key: /org/gnome/shell/weather/automatic-location
    value: "true"

  # if you use a different color scheme or font, overwrite these keys in your fork
  # see the keys/values on your own system with the command: dconf dump /
  # solarized dark
  - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color
    value: "'rgb(0,43,54)'"
  # solarized dark
  - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color
    value: "'rgb(131,148,150)'"
  # use solarized palette
  - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/palette
    value: "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']"
  # use powerline font provided + installed from this repo
  - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font
    value: "'JetbrainsMono Medium 10'"

  # Backslide parameters
  - key: /org/gnome/shell/extensions/backslide/delay
    value: "416"    # 6 hours

wallpapers:
  # directory to store wallpapers
  directory: ~/Pictures/wallpapers
  # only download if set to true
  # downloading can take a awhile. some websites also think you're scraping them
  download: false
  # put in wallpaper page - proper resolution will be selected + downloaded
  urls:
    - https://wallpaperscraft.com/wallpaper/moon_tree_starry_sky_132139
    - https://wallpaperscraft.com/wallpaper/deer_art_vector_134088
    - https://wallpaperscraft.com/wallpaper/ufos_aliens_cow_improvisation_vector_93569
    - https://wallpaperscraft.com/wallpaper/minimalism_sky_clouds_sun_mountains_lake_landscape_95458
    - https://wallpaperscraft.com/wallpaper/hills_landscape_minimalism_evening_sky_beauty_74526
    - https://wallpaperscraft.com/wallpaper/owl_bird_freddy_krueger_minimalism_93919
    - https://wallpaperscraft.com/wallpaper/road_asphalt_marking_130996
    - https://wallpaperscraft.com/wallpaper/autumn_benches_table_128676
    - https://wallpaperscraft.com/wallpaper/boat_mountains_lake_135258
    - https://wallpaperscraft.com/wallpaper/starry_sky_man_light_glitter_118118
    - https://wallpaperscraft.com/wallpaper/mountain_river_snow_winter_93245
    - https://wallpaperscraft.com/wallpaper/mountains_snow_summit_84607
    - https://wallpaperscraft.com/wallpaper/sculpture_starry_sky_stone_123440
