---
your_full_name: Kent Brockman
your_email: brockman.ks@gmail.com
# name your computer
hostname: phoenix
# install github.com/KentBrockman/dotfiles
# TODO: there is surely a way to let someone load their own dotfiles
install_dotfiles: True
preferred_shell: /usr/bin/zsh
install_battery_management_tools: true

firefox_profiles:
  default-release:
    extensions:
      # TODO: enable extensions after install. they are disabled by default
      # TODO: automatically configure extentions (e.g. tridactyl-vim URL ignore list)
      - ublock-origin
      - tridactyl-vim
      - lastpass-password-manager
      - gnome-shell-integration
    preferences:
      privacy.donottrackheader.enabled: "true"
      privacy.trackingprotection.enabled: "true"
      signon.rememberSignons: "false"
      datareporting.healthreport.uploadEnabled: "false"
      browser.ctrlTab.recentlyUsedOrder: "false"
      browser.search.defaultenginename: "'DuckDuckGo'"

# all the applications you like and want managed by snap
snap_applications:
  # music client
  - name: spotify
    classic: false
  # REST client
  - name: insomnia
    classic: false

# all the applications you like and want managed by apt
# TODO: pin versions?
apt_applications:
  # googles browser
  - google-chrome-stable
  # containerization engine + tooling
  - docker.io
  - docker-compose
  # team chat
  - slack-desktop
  # for making backups/restore points
  - timeshift
  # virtual machines
  - virtualbox
  # timer to help me work using pomodoro technique: https://en.wikipedia.org/wiki/Pomodoro_Technique
  - gnome-shell-pomodoro
  # view developer documentation offline. nice for working on an offline/airplane/roadtrip
  - zeal
  # image editor
  - gimp
  # for recording parts of screen and turning it into gifs
  - peek
  # 3D parametric modelling
  - freecad
  # great media player
  - vlc
  # sql database client
  - dbeaver-ce

# If using gnome, pick the extensions you like
# https://extensions.gnome.org/local/
# get id from extension URL
gnome_extension_ids:
  # Alt-Tab Switcher Popup Delay Removal
  - 1317
  # Sound Input & Output Device Chooser
  - 906
  # System Monitor
  - 120
  # Open Weather
  - 750
  # Removable Drive Menu
  - 7
  # Ubuntu AppIndicators - show app icons on top bar
  - 615

# links to debian packages to install
other_applications:
  # tool for making USB sticks that boot multiple OS's http://multibootusb.org
  # - https://github.com/mbusb/multibootusb/releases/download/v9.2.0/python3-multibootusb_9.2.0-1_all.deb

# gnome-desktop uses the dconf database under the hood for managing settings
# dconf is a key-value storage and how you specify values can be a little finicky
# see this for a good guide: https://docs.ansible.com/ansible/latest/modules/dconf_module.html#notes
# basically: make sure values have single quotes around them so ansibles dconf module parses them as strings
gnome_desktop_settings:
  # display temperatures in celsius
  - key: /org/gnome/GWeather/temperature-unit
    value: "'centigrade'"

  # invert scrolling so it is similar to MacOS. if you like windows scrolling set to false
  - key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
    value: "true"
    # use two fingers on the track pad to scroll
  - key: /org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled
    value: "true"

  # enable f.lux style blue-light reduction in display after sundown
  - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: "true"

  # determine where in the world we are for weather purposes
  - key: /org/gnome/shell/weather/automatic-location
    value: "true"

  # if you use a different color scheme or font, overwrite these keys in your fork
  # see the keys/values on your own system with the command: dconf dump /
  # solarized dark
  - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color
    value: "'rgb(0,43,54)'"
  # solarized dark
  - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color
    value: "'rgb(131,148,150)'"
  # use solarized palette
  - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/palette
    value: "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']"
  # use powerline font provided + installed from this repo
  - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font
    value: "'Monaco for Powerline 10'"

  # Escape is a far more useful key than capslock (at least for vim users) so remap it to escape
  - key: /org/gnome/desktop/input-sources/xkb-options
    value: "['caps:escape']"
