---
- hosts: localhost
  connection: local
  vars_files:
    - config.yml
    - config.custom.yml

  pre_tasks:
    - name: update packages
      become: true
      apt:
        update_cache: yes
      changed_when: False
    - name: install python dependencies for playbook
      pip:
        name:
          # TODO: pyenv and where I've PATH'd it hijacks system ansible. unsure what to do about this
          # HACK: Should this be a handler? Repeated in tasks/python-dev.yml. let pyenv manage it? redo path? i dunno
          # all of these dependencies are needed for ansible to run properly. experimentally discovered...
          - ansible
          - requests
          - psutil

  tasks:
    - name: set hostname
      tags: ["hostname"]
      hostname:
        name: "{{ hostname }}"
        use: systemd

    - name: add run-dev-playbook to local scripts
      tags: ["run-dev-playbook"]
      template:
        src: "{{ playbook_dir }}/files/run-dev-playbook.sh"
        dest: ~/.local/bin/run-dev-playbook.sh
        mode: 0544

    - import_tasks: tasks/web-browser.yml
      tags: ["web-browser"]
    - import_tasks: tasks/vscode.yml
      tags: ["vscode"]
    - import_tasks: tasks/dotfiles.yml
      tags: ["dotfiles"]
      when: install_dotfiles
    - import_tasks: tasks/terminal.yml
      tags: ["terminal"]
    - import_tasks: tasks/neovim.yml
      tags: ["neovim"]
    - import_tasks: tasks/applications.yml
      tags: ["applications"]
    - import_tasks: tasks/tmux-plugins.yml
      tags: ["tmux-plugins"]
    - import_tasks: tasks/vim-plugins.yml
      tags: ["vim-plugins"]
    - import_tasks: tasks/gnome-desktop.yml
      tags: ["gnome-desktop"]
    - import_tasks: tasks/battery-management.yml
      tags: ["battery-management"]
      when: install_battery_management_tools
    - import_tasks: tasks/python-dev.yml
      tags: ["python-dev"]
    - import_tasks: tasks/ops-dev.yml
      tags: ["ops-dev"]
    - import_tasks: tasks/remote-access.yml
      tags: ["remote-access"]
    - import_tasks: tasks/sync-content.yml
      tags: ["sync-content"]
      when: sync_content
