---
- hosts: localhost
  connection: local
  vars_files:
    - config.yml
  tasks:
    - import_tasks: tasks/editor.yml
      tags: ['editor']
    - import_tasks: tasks/terminal.yml
      tags: ['terminal']
    - import_tasks: tasks/applications.yml
      tags: ['applications']
