---
- hosts: localhost
  connection: local
  vars_files:
    - config.yml

  roles:
    # TODO: search engines
    - name: firefox
      role: basvandenbrink.firefox
      tags: ["firefox"]

    - name: install gnome_extensions
      role: jaredhocutt.gnome_extensions
      tags: ["gnome_extensions"]

  pre_tasks:
    - name: update packages
      become: true
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: set hostname
      hostname:
        name: "{{ hostname }}"
    - import_tasks: tasks/editor.yml
      tags: ["editor"]
    - import_tasks: tasks/terminal.yml
      tags: ["terminal"]
    - import_tasks: tasks/applications.yml
      tags: ["applications"]
    - import_tasks: tasks/tmux-plugins.yml
      tags: ["tmux-plugins"]
    - import_tasks: tasks/vim-plugins.yml
      tags: ["vim-plugins"]
    - import_tasks: tasks/gnome-desktop.yml
      tags: ["gnome-desktop"]
    - import_tasks: tasks/battery-management.yml
      tags: ["battery-management"]
      when: install_battery_management_tools
    - import_tasks: tasks/python-dev.yml
      tags: ["python-dev"]
