- name: markosamuli.pyenv
  version: v4.0.2
- name: andrewrothstein.unarchive-deps
  version: v1.1.5
- name: jaredhocutt.gnome_extensions
  version: master
- name: spk.syncthing-debian
  version: v2.4.0
- name: basvandenbrink.firefox
  version: master
- name: andrewrothstein.starship
  version:  v1.0.8
- name: suzuki-shunsuke.pyenv-module
  version:  v2.3.1
