- markosamuli.pyenv, v3.0.1
- andrewrothstein.unarchive-deps, v1.1.5
- jaredhocutt.gnome_extensions, master
- spk.syncthing-debian, v2.4.0
- basvandenbrink.firefox, master
- andrewrothstein.starship, v1.0.8
