---
# https://galaxy.ansible.com/markosamuli/pyenv
- name: markosamuli.pyenv
  version: v5.0.0

# https://galaxy.ansible.com/jaredhocutt/gnome_extensions
- name: jaredhocutt.gnome_extensions
  version: master

# https://github.com/basvandenbrink/ansible-firefox
- name: basvandenbrink.firefox
  version: master

# https://github.com/andrewrothstein/ansible-starship
- name: andrewrothstein.starship
  version: v1.0.8

# https://github.com/suzuki-shunsuke/ansible-pyenv-module
- name: suzuki-shunsuke.pyenv-module
  version: v2.3.1
