---
- name: Configure Marissa's machine
  hosts:
  - pegasus

  vars:
    # determine where the playbook is on the target machine
    # when local: use playbook_dir, which is a built in var for where playbook is on the host
    # when on ssh: dev_playbook_checkout_dir is supplied by host or group vars to check it out
    dev_playbook_directory: "{{ playbook_dir if ansible_connection == 'local' else dev_playbook_checkout_dir }}"

  pre_tasks:
    - name: Update packages
      become: true
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  tasks:

    # make it easy to run this playbook
    - name: Ensure various directories exist
      ansible.builtin.file:
        dest: "{{ item }}"
        state: directory
      with_items:
        - ~/.local/bin
        - ~/code

    - name: Make sure this repo exists on dev box
      ansible.builtin.git:
        repo: https://github.com/kentbrockman/dev-playbook.git
        dest: ~/code/dev-playbook/
        update: false

    - name: Set up nice terminal experience
      ansible.builtin.import_tasks: tasks/terminal.yml
      tags:
        - terminal

    - name: Set up remote access options (e.g. ssh)
      ansible.builtin.import_tasks: tasks/remote-access.yml
      tags:
        - remote-access

    - name: Set up nice gnome-desktop experience
      ansible.builtin.import_tasks: tasks/gnome-desktop.yml
      tags:
        - gnome-desktop
