#!/bin/bash
# show loading cause i'm trying to figure out order and when these are called for login/non login/ssh shells
# echo '.aliases loaded'

# Naviation Helpers
alias ~='cd ~'
alias .='cd ..'
alias ..='cd ../..'
alias ...='cd ../../..'
alias ....='cd ../../../..'

# Git Helpers
alias st='git status'
alias gd='git diff'
alias gdw='git diff --word-diff'

# Directory Listing Helpers
alias la='ls -al'
alias lah='ls -alh'

# disk space
alias diskusage='du -h -d 1 .'

alias ssh-key-make='ssh-keygen -t rsa -b 2048 -C'

if [ -f "~/.cmds/env-cd" ]; then
    alias env-cd='~/.cmds/env-cd.py';
    source ~/.cmds/env-cd;
fi

if [ -f "~/.cmds/open" ]; then
    alias open='~/.cmds/open';
fi

if [ $(command -v docker) ]; then
    alias ctop='docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest'
fi

# use neovim in place of vim if installed
if [ $(command -v nvim) ]; then
    alias vim='nvim'
fi

# nice tool replacements
if command -v prettyping &> /dev/null
then
    alias ping=prettyping
fi

if command -v batcat &> /dev/null
then
    alias less=batcat
    alias cat=batcat
fi
