# .zshrc sourced on interactive shells
# http://zsh.sourceforge.net/Intro/intro_3.html
# echo '.zshrc loaded'

# https://www.cyberciti.biz/faq/redhat-linux-pathmunge-command-in-shell-script/
pathmunge () {
	if ! echo $PATH | /bin/egrep -q "(^|:)$1($|:)" ; then
		if [ "$2" = "after" ] ; then
			PATH=$PATH:$1
		else
			PATH=$1:$PATH
		fi
	fi
}

# list directories you wish to have on your path
pathmunge "$HOME/.local/bin"
pathmunge "$HOME/.cmds"

# Use root profile for common stuff 
source ~/.aliases

# disable software flow control
# https://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator
stty -ixon

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# use oh-my-zsh for nice tab-autocompletion on specific commands
plugins=(
	vagrant
	terraform
)
source ~/.oh-my-zsh/oh-my-zsh.sh

# Add generated tab autocompletion flags to these programs
# It is better than nothing
if [ $(command -v mc) ]; then complete -o nospace -C $(which mc) mc; fi;

# add ability to load bash completion files
# https://stackoverflow.com/questions/3249432/can-a-bash-tab-completion-script-be-used-in-zsh
# autoload -U +X bashcompinit && bashcompinit

# starship for prompt goodness
if [ $(command -v starship) ]; then; eval "$(starship init zsh)"; fi;

# initialize pyenv if installed
# BUG: if in zshenv (which might be nice so pyenv is on all shells) vim buffers become super slow
# unsure how to troubleshoot this at this time
if [ -d "$HOME/.pyenv/bin" ]; then
	pathmunge "$HOME/.pyenv/bin"
fi
if [ $(command -v pyenv) ]; then
	# BUG: this will create a duplicate path entry for ~/.pyenv/shims
	# this is because pyenv init - doesn't set PATH using pathmunge
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

# set up hustory
# http://zsh.sourceforge.net/Doc/Release/Options.html#index-APPEND_005fHISTORY
HISTFILE=~/.zsh_history
# append to the history file, don't overwrite it
setopt APPEND_HISTORY

if [ $(command -v fzf) ]; then
	# use ripgrep to find files before passing them to fzf (default is find, which doesnt respect .gitignore)
	# export FZF_DEFAULT_COMMAND="rg --files ."

	# Append this line to ~/.zshrc to enable fzf keybindings for Zsh:
	# To see this in action:
	# type <CTRL-R> for reverse search
	# type <CTRL-T> for file search
	# type <ALT-C> for cd
	source /usr/share/doc/fzf/examples/key-bindings.zsh

	# Append this line to ~/.zshrc to enable fuzzy auto-completion for Zsh:
	# To see in action, type any of the following:
	# less **<TAB>
	# unset **<TAB>
	# export **<TAB>
	# unalias **<TAB>
	# cd **<TAB> or cd ../**<TAB>
	source /usr/share/doc/fzf/examples/completion.zsh
fi
