# .zshrc sourced on interactive shells
# http://zsh.sourceforge.net/Intro/intro_3.html
# echo '.zshrc loaded'

# https://www.cyberciti.biz/faq/redhat-linux-pathmunge-command-in-shell-script/
pathmunge () {
	if ! echo $PATH | /bin/egrep -q "(^|:)$1($|:)" ; then
		if [ "$2" = "after" ] ; then
			PATH=$PATH:$1
		else
			PATH=$1:$PATH
		fi
	fi
}

# list directories you wish to have on your path
pathmunge "$HOME/.local/bin"
pathmunge "$HOME/.cmds"

# Use root profile for common stuff 
source ~/.aliases

# disable software flow control
# https://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator
stty -ixon

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# source additional
if [ $(test -f ~/.zshrc.d) ]; then
  for file in $(ls ~/.zshrc.d); do
    source $file
  done
fi

# use oh-my-zsh for nice tab-autocompletion on specific commands
# TODO: load plugins from variable source zshrc.d files before sourcing oh-my-zsh
plugins=(
	vagrant
	terraform
)
source ~/.oh-my-zsh/oh-my-zsh.sh

# Add generated tab autocompletion flags to these programs
# It is better than nothing
if [ $(command -v mc) ]; then complete -o nospace -C $(which mc) mc; fi;

# add ability to load bash completion files
# https://stackoverflow.com/questions/3249432/can-a-bash-tab-completion-script-be-used-in-zsh
# autoload -U +X bashcompinit && bashcompinit

# starship for prompt goodness
if [ $(command -v starship) ]; then; eval "$(starship init zsh)"; fi;

# set up history
# http://zsh.sourceforge.net/Doc/Release/Options.html#index-APPEND_005fHISTORY
HISTFILE=~/.zsh_history
# append to the history file, don't overwrite it
setopt APPEND_HISTORY

# >>> conda initialize >>>
# TODO: this hijacks my default python environment. make this conditional based on projects or something?
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/home/kent/.pyenv/versions/anaconda3-2021.05/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/home/kent/.pyenv/versions/anaconda3-2021.05/etc/profile.d/conda.sh" ]; then
#         . "/home/kent/.pyenv/versions/anaconda3-2021.05/etc/profile.d/conda.sh"
#     else
#         export PATH="/home/kent/.pyenv/versions/anaconda3-2021.05/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<

