---
- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install applications via unappr
  ansible.builtin.include_role:
    name: "unappr"

- name: Install applications via flatpak
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  with_items: "{{ flatpak_applications | default([]) }}"

- name: Install standalone binaries
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: +x
  with_items: "{{ binary_applications | default([]) }}"

- name: Install applications via apt
  become: true
  ansible.builtin.apt:
    pkg: "{{ apt_applications | default([]) }}"

- name: Install deb packages from network
  become: true
  ansible.builtin.apt:
    deb: "{{ item }}"
  with_items: "{{ deb_packages | default([]) }}"

- name: Docker group exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Ensure current user is in docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    group: docker
    append: true
