---
- name: install snapd
  become: true
  apt:
    name: snapd
    state: present

- name: install applications via snap
  become: true
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  with_items:
    - name: slack
      classic: true
    - name: spotify
      classic: false
    - name: docker
      classic: false

- name: docker group exists
  become: true
  group:
    name: docker
    state: present

- name: ensure current user is in docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    group: docker
    append: yes

- name: install applications via apt
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - timeshift
    - virtualbox
