---
# see https://support.system76.com/articles/battery/
- name: install system76 recommended battery utilities
  become: true
  apt:
    name:
      - tlp
      - tlp-rdw
      - powertop
    install_recommends: no
