---
# see https://support.system76.com/articles/battery/
- name: Install system76 recommended battery utilities
  become: true
  ansible.builtin.apt:
    name:
      - tlp
      - tlp-rdw
      - powertop
    install_recommends: false
