---
- name: Directories exist
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - ~/.vim
    - ~/.zshrc.d

- name: Install dotfiles to home directory
  ansible.builtin.file:
    src: "{{ dev_playbook_directory }}/files/dotfiles/{{ item }}"
    dest: "~/.{{ item }}"
    force: true
    # symlink so improvements to any dotfile can be source controlled easily
    state: link
  with_items:
    - aliases
    - bashrc
    - gitignore_global
    - tmux.conf
    - vimrc
    # will fail to link if this directory already exists
    # delete or rename it
    # TODO: handle this seperately
    # - vim/colors
    - zshrc
    - cmds
    # for remapping capslock to escape
    # HACK: only works for x-window sessions, not TTYs or wayland
    # https://superuser.com/questions/729585/remap-keys-without-xmodmap-or-any-x-tools
    - Xmodmap
    - xinitrc

- name: Find all zshrc configuration extensions
  ansible.builtin.find:
    paths: "{{ dev_playbook_directory }}/files/zshrc.d"
    patterns: "*"
    recurse: false
    file_type: file
  register: zshrc_extensions

# https://unix.stackexchange.com/a/4040
- name: Install zshrc configuration extensions
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "~/.zshrc.d/{{ item.path | basename }}"
    force: true
    # symlink so improvements to any dotfile can be source controlled easily
    state: link
  with_items: "{{ zshrc_extensions.files }}"

- name: Install gitconfig
  tags:
    - gitconfig
  ansible.builtin.template:
    src: "files/dotfiles/gitconfig"
    dest: "~/.gitconfig"
