---
- name: dependencies for managing gnome-desktop settings via ansible
  become: true
  apt:
    name:
      # package for recording system resource (CPU, RAM, etc) information
      - python3-psutil
      # lots of extra gnome customizations
      - gnome-tweaks
      - unzip

- name: install gnome extensions
  import_role:
    name: jaredhocutt.gnome_extensions

# allow all verions of gnome extentions
# this can cause stability issues but many useful extentions arent quickly updated
# gsettings set org.gnome.shell disable-extension-version-validation "true"
- name: set GNOME desktop preferences
  dconf:
    key: "{{ item.key | string }}"
    value: "{{ item.value }}"
  with_items: "{{ gnome_desktop_settings }}"

- name: get wallpapers
  tags: ["wallpapers"]
  import_tasks: tasks/wallpapers.yml
