---
- name: dependencies for managing gnome-desktop settings via ansible
  become: true
  apt:
    name:
      - python3-psutil
      - gnome-tweaks

- name: set GNOME desktop preferences
  dconf:
    key: "{{item.key | string}}"
    value: "{{item.value}}"
  with_items: "{{ gnome_desktop_settings }}"
