---
# TODO: install a node interpreter to home directory instead of using system
# TODO: use a node version manager. some options:
# https://github.com/nvm-sh/nvm/blob/master/README.md
# https://www.npmjs.com/package/nave
# https://www.npmjs.com/package/n
- name: Install nodejs and npm tools
  become: true
  ansible.builtin.apt:
    name:
      - nodejs
      - npm

# HACK: use npx to run npm executables as binaries not in PATH
- name: Install global dev packages
  become: true
  community.general.npm:
    name: "{{ item.name }}"
    global: true
    state: latest
  with_items:
    - name: yarn
    - name: neovim
