# pyenv global system requires python and pip to be discoverable on path
# ubuntu >=20.04 doesnt ship with these
# for that, let's make sure a python/pip executable are available to user/on path
# this is also just generally handy for using python/pip keywords
---
- name: link python3 executables
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - src: /usr/bin/python3
      dest: ~/.local/bin/python
    - src: /usr/bin/pip3
      dest: ~/.local/bin/pip
