# pyenv global system requires python and pip to be discoverable on path
# ubuntu >=20.04 doesnt ship with these
# for that, make sure a python/pip executable are available to user/on path
# this is also just generally handy for using python/pip keywords
---
- name: Check current destination
  ansible.builtin.stat:
    path: "{{ item.dest }}"
  register: target

- name: Link file
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  when: not target.stat.exists
