---
# This task depends on vim-plugins
# Specifically - my neovim config heavily depends on vim configuration

- name: install neovim
  vars:
    applications:
      # TODO: install from github....
      - name: neovim
        provider: apt
  include_role:
    name: "unappr"

- name: install neovim config
  file:
    src: "{{ dev_playbook_directory }}/files/neovim"
    dest: "~/.config/nvim"
    state: link

- name: install neovim dependencies
  become: true
  apt:
    name:
      - ruby-dev

- name: install neovim pip package
  pip:
    name:
      - neovim
    state: latest

- name: install neovim gem
  become: true
  gem:
    name: neovim
    state: present
    user_install: false
