---
# This task depends on vim-plugins
# Specifically - my neovim config heavily depends on vim configuration

- name: Install neovim
  vars:
    applications:
      # TODO: install from github....
      - name: neovim
        provider: apt
  ansible.builtin.include_role:
    name: "unappr"

- name: Install neovim config
  ansible.builtin.file:
    src: "{{ dev_playbook_directory }}/files/neovim"
    dest: "~/.config/nvim"
    state: link

- name: Install neovim dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ruby-dev

- name: Install neovim pip package
  ansible.builtin.pip:
    name:
      - neovim
    state: latest

- name: Install neovim gem
  become: true
  community.general.gem:
    name: neovim
    state: present
    user_install: false
