---
- name: Check terraform install
  ansible.builtin.stat:
    path: ~/.local/bin/terraform
  register: terraform

- name: Install terraform
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
    dest: ~/.local/bin/
    remote_src: true
  when: not terraform.stat.exists

# if installing vagrant-libvirt
# include these apt packages: libvirt-dev libvirt-clients
# ensure libvirtd is running. ensure qemu-kvm is installed
