# Install tools for python development
# pyenv - tool for quicky changing python versions and virtualenvs
# pyenv's shim system CAN hijack env python,python2 and python3 where no the package or binaries you need may not be installed
# If ANY of python environments are having problems, 95% of the time it is a matter of:
# - troubleshooting PATH resolutions
# - reverse engineering shell construction 
# - reading scripts to figure out who is referencing what
# - typing `which python` or `pyenv which python` a million times
# - then being satisfied there is no right way to do this
# It is good to remember ANY PYTHON INSTALL is just a collection of files installed god-knows-where on your machine and linked through path-based resolution mechanics, which are often haphazard
---
- name: install pyenv
  vars:
    # pyenv/virtualenv versions to install
    pyenv_version: "v1.2.21"
    pyenv_virtualenv_version: "v1.1.5"
    # Python versions to install
    pyenv_python_versions:
      - "3.7.9"
      - "3.8.6"
      - "2.7.18"
    # what python environment should be used by default
    pyenv_global: system
    pyenv_install_from_package_manager: false
    pyenv_detect_existing_install: true
    # Dont modify dotfiles - will do it our own way
    pyenv_init_shell: false
  import_role:
    name: markosamuli.pyenv

- name: confirm pyenv global is system
  copy:
    src: files/python-dev/pyenv_version
    dest: ~/.pyenv/version

- name: install additional python dev packages
  become: true
  apt:
    name:
      - tox
    state: present

- name: install development dependencies
  pip:
    name:
      - python-language-server
    state: latest

- name: add pyenv module
  tags: pyenv-environments
  import_role:
    name: suzuki-shunsuke.pyenv-module

# setup neovim Python providers in pyenv now that we have it
- name: set up virtual environments
  tags: pyenv-environments
  include_tasks: tasks/python-environment.yml
  with_items:
    # Python 2 neovim provider
    - virtualenv_name: neovim2
      version: 2.7.18
      packages:
        - neovim
    # Python 3 neovim provider
    - virtualenv_name: neovim3
      version: 3.7.9
      packages:
        - neovim
