---
- name: install pyenv
  vars:
    # pyenv/virtualenv versions to install
    pyenv_version: "v1.2.21"
    pyenv_virtualenv_version: "v1.1.5"
    # Python versions to install
    pyenv_python_versions:
      - "3.7.9"
      - "3.8.6"
      - "2.7.18"
    # what python environment should be used by default
    pyenv_global: system
    pyenv_install_from_package_manager: false
    pyenv_detect_existing_install: true
    # Dont modify dotfiles - will do it our own way
    pyenv_init_shell: false
  import_role:
    name: markosamuli.pyenv

- name: confirm pyenv global is system
  copy:
    src: files/python-dev/pyenv_version
    dest: ~/.pyenv/version

- name: install development dependencies
  pip:
    name:
      - python-language-server
    state: latest

# TODO: consider setting up neovim Python providers in pyenv now that we have it
