---
- name: install python3 for development
  become: true
  apt:
    name:
      - python3-dev
      - python3-pip
      - python3-tk

- name: install packages
  pip:
    name:
      - wheel
      - python-language-server
    executable: pip3
