# enable remote access tools
# e.g. ssh, vnc
---
- name: Install sshd
  become: true
  ansible.builtin.apt:
    name: openssh-server
    state: present

- name: Run sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
