# enable remote access tools
# e.g. ssh, vnc
---
- name: install sshd
  become: true
  apt:
    name: openssh-server
    state: present

- name: sshd running
  become: true
  service:
    name: sshd
    state: started
    enabled: yes
