- name: Confirm preferred_shell installed
  ansible.builtin.stat:
    path: "{{ preferred_shell }}"
  register: stat_results

- name: Set up root shell
  become: true
  when: stat_results.stat.exists
  block:
    - name: Set root user to preferred_shell
      ansible.builtin.user:
        name: root
        shell: "{{ preferred_shell }}"

    - name: Install zshrc to root
      ansible.builtin.copy:
        src: "files/dotfiles/zshrc_root"
        dest: /root/.zshrc
        owner: root
        group: root

    - name: Root config exists
      ansible.builtin.file:
        dest: /root/.config
        state: directory

    - name: Install starship config
      ansible.builtin.file:
        src: "{{ dev_playbook_directory }}/files/dotfiles/starship.toml"
        dest: "/root/.config/starship.toml"
        # symlink so improvements to any dotfile can be source controlled easily
        state: link
