---
- name: Install syncthing service
  become: true
  vars:
    # https://github.com/syncthing/syncthing/tags
    # review task 'define syncthing.service unit file' when updating
    syncthing_version: "1.18.5"
  block:
    - name: Add the release PGP key
      ansible.builtin.apt_key:
        url: https://syncthing.net/release-key.gpg
        state: present

    - name: Add the "stable" channel to APT sources
      ansible.builtin.apt_repository:
        repo: deb https://apt.syncthing.net/ syncthing stable
        state: present

    - name: Install syncthing
      ansible.builtin.apt:
        name: syncthing
        state: present
        update_cache: true

  # start syncthing as a system service so syncing happens without user logging in
  # this falls down when multiple users may want multiple syncthing agents running on a single box
- name: Define syncthing.service unit file
  become: true
  ansible.builtin.template:
    # HACK: this ought to be part of role above
    src: files/sync-content/syncthing.service
    dest: /etc/systemd/system/syncthing.service
    owner: root
    group: root
    mode: 0644

- name: Start syncthing.service
  become: true
  ansible.builtin.systemd:
    name: syncthing.service
    enabled: true
    daemon_reload: true

- name: Raise inotify limits cause we sync a lot of content
  # https://docs.syncthing.net/users/faq.html#inotify-limits
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^fs.inotify.max_user_watches'
    line: fs.inotify.max_user_watches=204800

    # sort out config and directories to share. how should we be doing this?
