---
- name: install terminal related packages
  become: true
  apt:
    pkg:
      - zsh
      - zsh-autosuggestions
      - tmux
      - vim
    
- name: check if dotfiles are installed
  stat:
    path: ~/dotfiles
  register: dotfiles

- name: install dotfiles
  block:
    - name: checkout dotfiles
      git:
        repo: https://github.com/kentbrockman/dotfiles
        dest: ~/dotfiles

    - name: install dotfiles
      command: ~/dotfiles/install.sh
  when: dotfiles.stat.exists == False or install_dotfiles == True

- name: Install oh-my-zsh
  git: 
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

# apply patch to agnoster or copy in custom theme

# change default shell
# install powerline font
# install vim plugins
