---
- name: install terminal related packages
  become: true
  apt:
    pkg:
      # better shell and helper methods
      - zsh
      - zsh-autosuggestions
      # terminal multiplexer
      - tmux
      # cli text editor
      - vim
      # use clipboard from terminal
      - xclip

- name: check if dotfiles are installed
  stat:
    path: ~/dotfiles
  register: dotfiles

- name: install dotfiles
  block:
    - name: checkout dotfiles
      git:
        repo: https://github.com/kentbrockman/dotfiles
        dest: ~/dotfiles

    - name: install dotfiles
      command: ~/dotfiles/install.sh
  when: dotfiles.stat.exists == False and install_dotfiles == True

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

- name: confirm preferred shell executable is installed
  stat:
    path: "{{ preferred_shell }}"
  register: preferred_shell_executable

- name: set preferred shell for user
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ preferred_shell }}"
  when: preferred_shell_executable.stat.exists

- name: ensure local font directory exists
  file:
    name: ~/.local/share/fonts
    state: directory

- name: Monaco for Powerline font installed
  file:
    src: files/Monaco-for-Powerline.ttf
    dest: ~/.local/share/fonts/Monaco-for-Powerline.ttf
