---
- name: tmux plugin manager directory exists
  file:
    name: ~/.tmux/plugins
    state: directory

- name: install tmux plugin manager (tpm)
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    version: v3.0.0

# Note: must have plugin lines in tmux.conf uncommented for this to work
# TODO: when run via ansible-playbook, a prompt appears for github credentials. how to not have this?
- name: install tmux plugins
  command: ~/.tmux/plugins/tpm/bin/install_plugins

- name: periodically save tmux configuration
  cron:
    name: save tmux panes
    # run every 20 minutes: https://crontab.guru/#*/20_*_*_*_*
    minute: "*/20"
    # save tmux panes, do it quietly so I dont see it
    job: ~/.tmux/./plugins/tmux-resurrect/scripts/save.sh quiet
# TODO: include conditional in tmux.conf - reload tmux if there is a save?
