---
- name: Tmux plugin manager directory exists
  ansible.builtin.file:
    name: ~/.tmux/plugins
    state: directory

- name: Install tmux plugin manager (tpm)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    version: v3.0.0

- name: Detect tmux plugins requested to be installed
  ansible.builtin.shell: awk '/@plugin/ {print $NF}' ~/.tmux.conf | sed "s/'//g" | awk -F"/" '{print $2}'
  register: plugins_requested
  changed_when: false

- name: Detect plugins already installed
  ansible.builtin.shell: ls -1 $HOME/.tmux/plugins | grep -v 'tpm'
  register: plugins_installed
  changed_when: false

- name: Install tmux plugins
  ansible.builtin.command: ~/.tmux/plugins/tpm/bin/install_plugins
  environment:
    # needs to be set for plugins to install
    # this is a fairly standard place for tmux plugins
    # but the hardcoding is still bad
    # TODO: do not hardcode or at least infer first
    # maybe set in config.yml?
    TMUX_PLUGIN_MANAGER_PATH: $HOME/.tmux/plugins
  when: plugins_installed.stdout_lines | difference(plugins_requested.stdout_lines)

- name: Save tmux configuration script
  ansible.builtin.copy:
    src: save_tmux_configuration.sh
    dest: ~/.tmux/save_tmux_configuration.sh
    mode: +x

- name: Periodically save tmux configuration
  ansible.builtin.cron:
    name: save tmux panes
    # run every 20 minutes: https://crontab.guru/#*/20_*_*_*_*
    minute: "*/20"
    # save tmux panes quietly so I dont see it
    # dont save panes unless tmux server is running otherwise we overwrite our old configuration
    job: ~/.tmux/save_tmux_configuration.sh
