---
- name: tmux plugin manager directory exists
  file:
    name: ~/.tmux/plugins
    state: directory

- name: install tmux plugin manager (tpm)
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    version: v3.0.0

# Note: must have plugin lines in tmux.conf uncommented for this to work
# TODO: this is always marked changed cause we run a command. can you make this more idempotent?
- name: install tmux plugins
  command: ~/.tmux/plugins/tpm/bin/install_plugins
  environment:
    # needs to be set for plugins to install
    # this is a fairly standard place for tmux plugins
    # but the hardcoding is still bad
    # TODO: do not hardcode or at least infer first
    # maybe set in config.yml?
    TMUX_PLUGIN_MANAGER_PATH: $HOME/.tmux/plugins/

- name: periodically save tmux configuration
  cron:
    name: save tmux panes
    # run every 20 minutes: https://crontab.guru/#*/20_*_*_*_*
    minute: "*/20"
    # save tmux panes quietly so I dont see it
    # dont save panes unless tmux server is running otherwise we overwrite our old configuration
    job: tmux server-info &> /dev/null; if [[ $? == 0 ]]; then ~/.tmux/plugins/tmux-resurrect/scripts/save.sh quiet; else echo "tmux server not running. dont save session"; fi
# TODO: include conditional in tmux.conf - reload tmux panes on tmux start if there is a save available
