---
- name: vim plugin manager directory exists
  file:
    name: "~/.vim/{{ item }}"
    state: directory
  with_items:
    - autoload
    - plugged

- name: install vim plugin manager (vim-plug)
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/0.10.0/plug.vim
    dest: ~/.vim/autoload/plug.vim

# If this step fails, double check plugin statements in .vimrc
- name: install vim plugins
  command: vim +PlugInstall +qall

- name: install vim plugin dependencies
  pip:
    name:
      - msgpack
    state: latest
