- name: create wallpapers directory
  file:
    dest: "{{ wallpapers.directory }}"
    state: directory

- name: determine screen resolution
  shell: "xrandr --screen 0 | grep ' connected' | awk '{ print $4 }'"
  register: xrandr_output
  changed_when: false

- name: parse resolution out of xrandr output
  set_fact:
    screen_resolution: "{{ xrandr_output.stdout_lines[0] | regex_replace('\\+.*$', '') }}"

- name: get wallpapers from http://wallpaperswide.com/
  get_url:
    url: "{{ item }}"
    dest: "{{ wallpapers.directory }}/{{ item | basename }}"
  # modify URL to resolution-appropriate version
  with_items: '{{ wallpapers.urls | map("regex_replace", ".com", ".com/download") | map("regex_replace", "s.html", "-" + screen_resolution + ".jpg") }}'

- name: get images list
  # need to do this cause dconf needs a very specific string format
  shell: ls -d {{ wallpapers.directory }}/* | python -c "import sys, os; print(list([x.replace(os.linesep, '') for x in sys.stdin]))"
  register: images
  changed_when: false

- name: update backslide images
  dconf:
    key: /org/gnome/shell/extensions/backslide/image-list
    value: "{{ images.stdout_lines[0] }}"
