---
- name: Converge
  hosts: all
  tasks:
    - name: "Include unappr"
      ansible.builtin.include_role:
        name: "unappr"
      vars:
        applications:
          - name: test_package
            provider: executable
            url: https://kbr-assets.s3.us-west-1.amazonaws.com/helloworld
            exec_name: hworld
