---
- name: "uninstall {{ app.name }} from apt"
  become: ansible_facts.user_id == 'root' or false | bool
  apt:
    name: "{{ catalog[app.name].providers.apt.name }}"
    state: absent
    autoremove: yes
