---
- name: "Uninstall from apt: {{ app.name }}"
  become: "{{ 'yes' if ansible_facts.user_id != 'root' else 'no' }}"
  ansible.builtin.apt:
    name: "{{ catalog[app.name].providers.apt.name }}"
    state: absent
    autoremove: true
