---
- name: "uninstall {{ app.name }} from apt"
  become: "{{ 'yes' if ansible_facts.user_id != 'root' else 'no' }}"
  apt:
    name: "{{ catalog[app.name].providers.apt.name }}"
    state: absent
    autoremove: yes
