---
# https://docs.ansible.com/ansible/2.9/modules/flatpak_module.html#flatpak-module
# flatpak module doesnt support versioning very well
# It is also tricky to do via flatpak directly
- name: install with version
  fail:
    msg: |
      "unappr cannot support flatpak versioning and this time.

      If you want to version from flatpak, follow:
      1. Remove the 'version' section from applications config
      2. Show versions: flatpak remote-info --log flathub <YOUR PACKAGE>
      3. Set package to commit: flatpak update --commit=<COMMIT> <YOUR PACKAGE>

      Source:
      https://github.com/flatpak/flatpak/issues/3097#issuecomment-530583469"
  when: "'version' in app"

- name: "install {{ app.name }} from flatpak"
  flatpak:
    name: "{{ catalog[app.name].providers.flatpak.application_id }}"
    state: present
    method: user
