---
- name: "uninstall {{ app.name }} from flatpak"
  # TODO: conditional on method: user/system
  become: "{{ true if ansible_facts.user_id != 'root' else false }}"
  flatpak:
    name: "{{ catalog[app.name].providers.flatpak.application_id }}"
    state: absent
  notify:
    - Uninstall unused flatpaks
