# Implement github provider
# Download .AppImage or Binaries from Github Releases
---
# TODO hit API to get latest
# curl https://api.github.com/repos/laurent22/joplin/releases
- debug:
    msg: "install_github_AppImage for {{ item.name }}"
