---
- name: Have flatpak runtime installed
  apt:
    name: flatpak

- name: executable directory exists
  file:
    path: "{{ executable_directory }}"
    state: directory

- name: Add the flathub flatpak repository remote to the user installation
  # https://docs.ansible.com/ansible/2.9/modules/flatpak_remote_module.html
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Begin handling applications
  include_tasks: unappr.yml
  with_items: "{{ applications }}"
  loop_control:
    loop_var: app
