---
- name: Have flatpak runtime installed
  become: "{{ 'yes' if ansible_facts.user_id != 'root' else 'no' }}"
  ansible.builtin.apt:
    name: flatpak

- name: Executable directory exists
  ansible.builtin.file:
    path: "{{ executable_directory }}"
    state: directory

- name: Add the flathub flatpak repository remote to the user installation
  become: "{{ 'yes' if ansible_facts.user_id != 'root' else 'no' }}"
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Begin handling applications
  ansible.builtin.include_tasks: unappr.yml
  with_items: "{{ applications }}"
  when: not target_apps
  loop_control:
    loop_var: app

- name: Begin handling targeted applications
  ansible.builtin.include_tasks: unappr.yml
  with_items: "{{ applications | selectattr('name', 'in', target_apps) | list }}"
  when: target_apps
  loop_control:
    loop_var: app
