---
- name: "Confirm {{ app.name }} in catalog"
  assert:
    that:
      - app.name in catalog
    success_msg: "{{ app.name }} is in catalog"
    # TODO: link to the application catalog
    fail_msg: "{{ app.name }} does not appear to be in catalog. Please submit a PR to update the catalog."

- name: "Confirm {{ app.name }} is available from {{ app.provider }}"
  assert:
    that:
      - "app.provider in catalog.{{ app.name }}.providers"
    success_msg: "{{ app.name }} is available from {{ app.provider }}"
    # TODO: link to the application catalog
    fail_msg: "{{ app.name }} is not available from {{ app.provider }}. Please submit a PR to update the catalog }}"

- include_tasks: "{{ app.provider }}_install.yml"

- name: "uninstall {{ app.name }} from other providers"
  include_tasks: "{{ provider }}_uninstall.yml"
  when: provider != app.provider
  loop: "{{ catalog[app.name].providers.keys()|list }}"
  loop_control:
    loop_var: provider
