---
- name: "Confirm {{ app.name }} in catalog"
  assert:
    that:
      - app.name in catalog
    success_msg: "{{ app.name }} is in catalog"
    # TODO: link to the application catalog
    fail_msg: "{{ app.name }} does not appear to be in catalog. Please submit a PR to update the catalog."

- name: "Confirm {{ app.name }} is available from {{ app.provider }}"
  assert:
    that:
      - "app.provider in catalog.{{ app.name }}.providers"
    success_msg: "{{ app.name }} is available from {{ app.provider }}"
    # TODO: link to the application catalog
    fail_msg: "{{ app.name }} is not available from {{ app.provider }}. Please submit a PR to update the catalog }}"
  # executable will never be specific in the catalog of providers
  when: app.provider != "executable"

- name: "install {{ app.name }} from {{ app.provider }}"
  include_tasks: "{{ app.provider }}_install.yml"

- name: "uninstall {{ app.name }} from other providers"
  include_tasks: "{{ provider }}_uninstall.yml"
  when: provider != app.provider
  loop: "{{ catalog[app.name].providers | default({}) | dict2items | map(attribute='key') | list }}"
  loop_control:
    loop_var: provider

# not sure how to fold this into loop in the previous task
- name: "uninstall {{ app.name }} executable"
  include_tasks: "executable_uninstall.yml"
  when: app.provider != "executable"
