#!/bin/bash
# open a file with the default program

if [[ -z $1 ]]; then
    # no argument provided - use fzf to search for them
    FILES=$(fzf -m)
else
    # open file specified in argument
    FILES=$@
fi

for file in $FILES; do
  xdg-open $file;
done
