---
- name: Converge
  hosts: all
  tasks:
    - name: "Include unappr"
      ansible.builtin.include_role:
        name: "unappr"
      vars:
        applications:
          - name: test_package
            provider: flatpak
